server:
  port: 5001

management:
  endpoint:
    shutdown:
      enabled: true
             
  endpoints:
    web:
      exposure:
        include:
        - "*" 
      base-path: /olx-login-monitor  
spring: application:  name: login-service
 data:
   mongodb:
    host: localhost
    port: 27017
    database: userDB 
 zipkin:
    base-url:
     http://localhost:9411
 config:
   import:
    configserver:http://localhost:8888   
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address:
     true
    hostname:
     localhost  
      
 
  
   