server:
  port: 5002
management:  endpoints:    web:      exposure:        include:        - "*"
      base-path: /olx-advertise-monitor  
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always                shutdown:      enabled: true
eureka:
 client:
   register-with-eureka: true
   fetch-registry: true
 instance:
    prefer-ip-address:
     true
    hostname:
     localhost    
spring:
 application:
  name: Advertise-service
 config:
   import:
    configserver:http://localhost:8888 
 zipkin:
  base-url:
     http://localhost:9411
 main:
    allow-bean-definition-overriding: true

 
      
resilience4j:
  circuitbreaker:
    instances:
      CATEGORY-CIRCUIT-BREAKER:
        registerHealthIndicator: true
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10s  