server:
  port: 5003
  
spring:
 application:
  name: masterdata-service
 zipkin:
    base-url:
     http://localhost:9411
 config:
   import:
    configserver:http://localhost:8888   
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address:
     true
    hostname:
     localhost  
management:
  endpoint:
    shutdown:
      enabled: true
             
  endpoints:
    web:
      exposure:
        include:
        - "*" 
      base-path: /olx-masterdata-monitor            