server:
  port: 9090

spring:
 datasource:
  url: jdbc:mysql://localhost:3306/stocks_db
  driver-class-name: com.mysql.cj.jdbc.Driver
  username: root
  password: root@123
 jpa:
  hibernate.ddl-auto: update
  properties:
   hibernate:
   dialect: org.hibernate.dialect.MySQL8Dialect  
 application:
    name: DefaultApp
 profiles:
    active:
    - dev   
 data:
  mongodb:
   host: localhost
   port: 27017
   database: stockdb
   